server:
    type: simple
    applicationContextPath: /
    adminContextPath: /admin
    connector:
        type: http
        port: 8085

inputDirectory: c:\Users\James\.timeline-loader\inputDirectory