server:
    type: simple
    applicationContextPath: /
    adminContextPath: /admin
    connector:
        type: http
        port: 8085

inputDirectory: /home/jc064522/.timeline-loader/inputDirectory
